#index:
#    path: /
#    controller: App\Controller\DefaultController::index
error404:
    path: /{wildcard}
    methods: ["GET"]
    controller: App\Controller\ErrorController::error404
    requirements:
        wildcard: ".*"

error403:
    path: /{wildcard}
    methods: ["GET"]
    controller: App\Controller\ErrorController::error403
    requirements:
        wildcard: ".*"

error500:
    path: /{wildcard}
    methods: ["GET"]
    controller: App\Controller\ErrorController::error500
    requirements:
        wildcard: ".*"

error:
    path: /{wildcard}
    methods: ["GET"]
    controller: App\Controller\ErrorController::error
    requirements:
        wildcard: ".*"